# Generated by Django 6.1 on 2026-10-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobtype",
                    models.CharField(
                        choices=[
                            ("DATA", "Данные и импорт"),
                            ("ETL", "Расчёты"),
                            ("PUBLISH", "Обновления"),
                            ("SERVICE", "Сервис"),
                        ],
                        default="DATA",
                        max_length=20,
                        verbose_name="Тип задачи",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Задача")),
                (
                    "command",
                    models.CharField(
                        help_text="Имя management-команды: python manage.py <команда> <id задачи>",
                        max_length=250,
                        unique=True,
                        verbose_name="Команда",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("SERVER", "Сервер"),
                            ("LOCAL", "Локалка"),
                            ("LOCSER", "Локалка / Сервер"),
                        ],
                        default="LOCAL",
                        max_length=20,
                        verbose_name="Область",
                    ),
                ),
                (
                    "param",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Параметры"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INACTIVE", "Не запускалась"),
                            ("PENDING", "Ожидает"),
                            ("RUNNING", "Выполняется"),
                            ("DONE", "Выполнено"),
                            ("FAILED", "Ошибка"),
                            ("CANCELED", "Отменено"),
                        ],
                        default="INACTIVE",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "lastrun",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний запуск"
                    ),
                ),
                (
                    "logfile",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="jobs/logs/",
                        verbose_name="Файл лога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Список команд",
                "ordering": ["jobtype", "name"],
            },
        ),
    ]
