# Generated by Django 6.1 on 2026-10-09 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MartItemMonth",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("month", models.DateField(verbose_name="Месяц")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Наряд (сервис)"),
                            ("sale", "Реализация"),
                            ("retail", "Розница"),
                            ("return", "Возврат"),
                            ("correction", "Корректировка"),
                            ("other", "Прочее"),
                        ],
                        max_length=12,
                        verbose_name="Канал",
                    ),
                ),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("cost", models.FloatField(verbose_name="Себестоимость")),
                ("docs", models.BigIntegerField(verbose_name="Документов")),
                ("lines", models.BigIntegerField(verbose_name="Строк")),
                (
                    "lines_no_revenue",
                    models.BigIntegerField(verbose_name="Строк без выручки"),
                ),
            ],
            options={
                "verbose_name": "Артикул × месяц",
                "verbose_name_plural": "Артикул × месяц",
                "db_table": "mart_item_month",
                "ordering": ["-month", "-revenue"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MartItemStats",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="mart_stats",
                        serialize=False,
                        to="catalog.item",
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "first_sale",
                    models.DateField(null=True, verbose_name="Первая продажа"),
                ),
                (
                    "last_sale",
                    models.DateField(null=True, verbose_name="Последняя продажа"),
                ),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("cost", models.FloatField(verbose_name="Себестоимость")),
                ("docs", models.BigIntegerField(verbose_name="Документов")),
                ("months", models.BigIntegerField(verbose_name="Месяцев с продажами")),
                (
                    "months_12",
                    models.BigIntegerField(
                        verbose_name="Месяцев с продажами за 12 мес."
                    ),
                ),
                ("qty_12", models.FloatField(verbose_name="Кол-во за 12 мес.")),
                ("qty_service", models.FloatField(verbose_name="Кол-во в нарядах")),
                ("qty_sale", models.FloatField(verbose_name="Кол-во в реализации")),
                ("qty_retail", models.FloatField(verbose_name="Кол-во в рознице")),
            ],
            options={
                "verbose_name": "Статистика артикула",
                "verbose_name_plural": "Статистика артикулов",
                "db_table": "mart_item_stats",
                "ordering": ["-revenue"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MartOrdersMonth",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("month", models.DateField(verbose_name="Месяц")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Наряд (сервис)"),
                            ("sale", "Реализация"),
                            ("retail", "Розница"),
                            ("return", "Возврат"),
                            ("correction", "Корректировка"),
                            ("other", "Прочее"),
                        ],
                        max_length=12,
                        verbose_name="Канал",
                    ),
                ),
                ("docs", models.BigIntegerField(verbose_name="Документов")),
                ("lines", models.BigIntegerField(verbose_name="Строк")),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("cost", models.FloatField(verbose_name="Себестоимость")),
            ],
            options={
                "verbose_name": "Документы × месяц",
                "verbose_name_plural": "Документы × месяц",
                "db_table": "mart_orders_month",
                "ordering": ["-month", "kind"],
                "managed": False,
            },
        ),
    ]
