# Generated by Django 6.1 on 2026-10-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MartGroupMonth",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("month", models.DateField(verbose_name="Месяц")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Наряд (сервис)"),
                            ("sale", "Реализация"),
                            ("retail", "Розница"),
                            ("return", "Возврат"),
                            ("correction", "Корректировка"),
                            ("other", "Прочее"),
                        ],
                        max_length=12,
                        verbose_name="Канал",
                    ),
                ),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("cost", models.FloatField(verbose_name="Себестоимость")),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                ("lines", models.BigIntegerField(verbose_name="Строк")),
                ("docs", models.BigIntegerField(verbose_name="Документов")),
                ("items", models.BigIntegerField(verbose_name="Артикулов")),
            ],
            options={
                "verbose_name": "Группы × месяц",
                "verbose_name_plural": "Группы × месяц",
                "db_table": "mart_group_month",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MartMeta",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("built_at", models.BigIntegerField(verbose_name="Пересчитано (unix)")),
                (
                    "last_month",
                    models.DateField(null=True, verbose_name="Последний месяц данных"),
                ),
                (
                    "last_date",
                    models.DateField(null=True, verbose_name="Последняя дата данных"),
                ),
                ("lines", models.BigIntegerField(verbose_name="Строк продаж")),
            ],
            options={
                "verbose_name": "Пересчёт витрин",
                "verbose_name_plural": "Пересчёт витрин",
                "db_table": "mart_meta",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MartSalesMonth",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("month", models.DateField(verbose_name="Месяц")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Наряд (сервис)"),
                            ("sale", "Реализация"),
                            ("retail", "Розница"),
                            ("return", "Возврат"),
                            ("correction", "Корректировка"),
                            ("other", "Прочее"),
                        ],
                        max_length=12,
                        verbose_name="Канал",
                    ),
                ),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("cost", models.FloatField(verbose_name="Себестоимость")),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                ("docs", models.BigIntegerField(verbose_name="Документов")),
                ("lines", models.BigIntegerField(verbose_name="Строк")),
                (
                    "lines_no_revenue",
                    models.BigIntegerField(verbose_name="Строк без выручки"),
                ),
                ("items", models.BigIntegerField(verbose_name="Артикулов")),
            ],
            options={
                "verbose_name": "Продажи × месяц",
                "verbose_name_plural": "Продажи × месяц",
                "db_table": "mart_sales_month",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MartSeason",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("season", models.BigIntegerField(verbose_name="Сезон (год начала)")),
                (
                    "season_month",
                    models.BigIntegerField(verbose_name="Месяц сезона (окт = 1)"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Наряд (сервис)"),
                            ("sale", "Реализация"),
                            ("retail", "Розница"),
                            ("return", "Возврат"),
                            ("correction", "Корректировка"),
                            ("other", "Прочее"),
                        ],
                        max_length=12,
                        verbose_name="Канал",
                    ),
                ),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("lines", models.BigIntegerField(verbose_name="Строк")),
            ],
            options={
                "verbose_name": "Сезонность",
                "verbose_name_plural": "Сезонность",
                "db_table": "mart_season",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MartServiceItems",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("month", models.DateField(verbose_name="Месяц")),
                ("orders", models.BigIntegerField(verbose_name="Нарядов")),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("cost", models.FloatField(verbose_name="Себестоимость")),
            ],
            options={
                "verbose_name": "Артикулы в нарядах",
                "verbose_name_plural": "Артикулы в нарядах",
                "db_table": "mart_service_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MartServiceMonth",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("month", models.DateField(verbose_name="Месяц")),
                ("orders", models.BigIntegerField(verbose_name="Нарядов")),
                (
                    "orders_consumable",
                    models.BigIntegerField(verbose_name="Нарядов с расходниками"),
                ),
                (
                    "orders_no_revenue",
                    models.BigIntegerField(verbose_name="Нарядов без выручки"),
                ),
                ("lines", models.BigIntegerField(verbose_name="Строк")),
                ("qty", models.FloatField(verbose_name="Кол-во")),
                (
                    "qty_consumable",
                    models.FloatField(verbose_name="Кол-во расходников"),
                ),
                ("revenue", models.FloatField(verbose_name="Выручка с НДС")),
                ("cost", models.FloatField(verbose_name="Себестоимость")),
            ],
            options={
                "verbose_name": "Наряды × месяц",
                "verbose_name_plural": "Наряды × месяц",
                "db_table": "mart_service_month",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="MartOrdersMonth",
        ),
    ]
