# Generated by Django 6.1 on 2026-10-09 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Латиницей, без пробелов. Связывает группу с правилами разметки — после создания не меняется.",
                        max_length=40,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Группа")),
                (
                    "demand_type",
                    models.CharField(
                        choices=[
                            ("consumable", "Расходники ТО"),
                            ("wear", "Износ"),
                            ("repair", "Ремонт"),
                            ("body", "Кузов"),
                            ("accessory", "Аксессуары"),
                            ("fastener", "Крепёж"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип спроса",
                    ),
                ),
                (
                    "sort",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Товарная группа",
                "verbose_name_plural": "Товарные группы",
                "ordering": ["sort", "name"],
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Техника")),
                (
                    "sort",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Техника",
                "verbose_name_plural": "Техника",
                "ordering": ["sort", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Без артикула в скобках",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "name_1c",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название в 1С"
                    ),
                ),
                (
                    "group_source",
                    models.CharField(
                        choices=[
                            ("rule", "Правило по названию"),
                            ("article", "Префикс артикула"),
                            ("manual", "Вручную"),
                            ("none", "Не распознано"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Чем определена группа",
                    ),
                ),
                (
                    "group_rule",
                    models.CharField(
                        blank=True,
                        help_text="Слово из названия или префикс артикула, по которым выбрана группа",
                        max_length=120,
                        verbose_name="Сработавшее правило",
                    ),
                ),
                (
                    "first_sale",
                    models.DateField(
                        blank=True, null=True, verbose_name="Первая продажа"
                    ),
                ),
                (
                    "last_sale",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последняя продажа"
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Выручка с НДС",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "docs",
                    models.PositiveIntegerField(default=0, verbose_name="Документов"),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="В скольких календарных месяцах артикул продавался",
                        verbose_name="Месяцев с продажами",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="catalog.itemgroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="catalog.platform",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Артикул",
                "verbose_name_plural": "Номенклатура",
                "ordering": ["-revenue"],
                "indexes": [
                    models.Index(
                        fields=["group", "-revenue"],
                        name="catalog_ite_group_i_246c8c_idx",
                    ),
                    models.Index(
                        fields=["group_source"], name="catalog_ite_group_s_bb286f_idx"
                    ),
                ],
            },
        ),
    ]
