# Generated by Django 6.1 on 2026-10-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_gear_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="family_head",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполняется сам по заменам номеров: на какой артикул переходят прогноз и статистика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family_members",
                to="catalog.item",
                verbose_name="Актуальный номер",
            ),
        ),
        migrations.CreateModel(
            name="ItemReplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rule9x", "Правило X → 9X"),
                            ("oil", "Семейство масел и химии"),
                            ("name", "Номер в названии"),
                            ("manual", "Вручную"),
                            ("client", "Таблица клиента"),
                        ],
                        max_length=10,
                        verbose_name="Откуда",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Действует"),
                            ("suggested", "Предложено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Комментарий"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "new",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replaces_links",
                        to="catalog.item",
                        verbose_name="Новый номер",
                    ),
                ),
                (
                    "old",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replaced_by_links",
                        to="catalog.item",
                        verbose_name="Старый номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замена номера",
                "verbose_name_plural": "Замены номеров",
                "ordering": ["status", "-updated"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("old", "new"), name="item_replacement_uniq"
                    )
                ],
            },
        ),
    ]
