# Generated by Django 6.1 on 2026-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_item_family_head_itemreplacement"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_new",
            field=models.BooleanField(
                default=False,
                help_text="Первая продажа (по всему семейству номеров) — за последние 6 месяцев. Короткая история: прогноз и запас проверять вручную. Ставится само при импорте",
                verbose_name="Новинка",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="new_since",
            field=models.DateField(
                blank=True,
                help_text="Первая продажа семейства — для новинок",
                null=True,
                verbose_name="Продаётся с",
            ),
        ),
    ]
