# Generated by Django 6.1 on 2026-10-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                ("data_end", models.DateField(verbose_name="Факт по")),
                (
                    "horizon",
                    models.PositiveSmallIntegerField(verbose_name="Горизонт, мес."),
                ),
                (
                    "params",
                    models.JSONField(default=dict, verbose_name="Параметры по рядам"),
                ),
                (
                    "tune_runs",
                    models.JSONField(
                        default=dict, verbose_name="Подбор, из которого параметры"
                    ),
                ),
                ("seconds", models.FloatField(default=0, verbose_name="Время, c")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз",
                "verbose_name_plural": "Прогнозы",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TuneRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("service", "Сервис (наряды)"),
                            ("shop", "Реализация и розница"),
                            ("total", "Всего"),
                        ],
                        max_length=20,
                        verbose_name="Ряд",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                ("data_end", models.DateField(verbose_name="Факт по")),
                (
                    "horizon",
                    models.PositiveSmallIntegerField(verbose_name="Горизонт, мес."),
                ),
                ("cutoffs", models.JSONField(default=list, verbose_name="Отсечки")),
                (
                    "combos",
                    models.PositiveIntegerField(default=0, verbose_name="Комбинаций"),
                ),
                ("seconds", models.FloatField(default=0, verbose_name="Время, c")),
                (
                    "best",
                    models.JSONField(default=dict, verbose_name="Лучшие параметры"),
                ),
                ("wape3", models.FloatField(null=True, verbose_name="Ошибка 1–3 мес.")),
                (
                    "wape6",
                    models.FloatField(null=True, verbose_name="Ошибка на горизонте"),
                ),
                ("bias", models.FloatField(null=True, verbose_name="Смещение")),
                (
                    "default_wape3",
                    models.FloatField(null=True, verbose_name="По умолчанию 1–3 мес."),
                ),
                (
                    "default_wape6",
                    models.FloatField(
                        null=True, verbose_name="По умолчанию на горизонте"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подбор параметров",
                "verbose_name_plural": "Подбор параметров",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TuneResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="Место")),
                ("params", models.JSONField(verbose_name="Параметры")),
                ("wape3", models.FloatField(verbose_name="Ошибка 1–3 мес.")),
                ("wape6", models.FloatField(verbose_name="Ошибка на горизонте")),
                ("bias", models.FloatField(verbose_name="Смещение")),
                ("score", models.FloatField(verbose_name="Оценка")),
                ("folds", models.JSONField(default=list, verbose_name="По отсечкам")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Prophet по умолчанию"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="forecast.tunerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат подбора",
                "verbose_name_plural": "Результаты подбора",
                "ordering": ["run", "rank"],
            },
        ),
        migrations.CreateModel(
            name="BacktestPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cutoff", models.DateField(verbose_name="Отсечка")),
                ("month", models.DateField(verbose_name="Месяц")),
                ("h", models.PositiveSmallIntegerField(verbose_name="Месяц вперёд")),
                ("actual", models.FloatField(verbose_name="Факт")),
                ("yhat", models.FloatField(verbose_name="Прогноз")),
                ("lower", models.FloatField(verbose_name="Нижняя граница")),
                ("upper", models.FloatField(verbose_name="Верхняя граница")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="forecast.tunerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка бэктеста",
                "verbose_name_plural": "Бэктест",
                "ordering": ["run", "cutoff", "month"],
            },
        ),
        migrations.CreateModel(
            name="ForecastPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("service", "Сервис (наряды)"),
                            ("shop", "Реализация и розница"),
                            ("total", "Всего"),
                        ],
                        max_length=20,
                        verbose_name="Ряд",
                    ),
                ),
                ("month", models.DateField(verbose_name="Месяц")),
                ("yhat", models.FloatField(verbose_name="Прогноз")),
                ("lower", models.FloatField(verbose_name="Нижняя граница")),
                ("upper", models.FloatField(verbose_name="Верхняя граница")),
                (
                    "actual_before",
                    models.FloatField(default=0, verbose_name="Факт до даты прогноза"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="forecast.forecastrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка прогноза",
                "verbose_name_plural": "Точки прогноза",
                "ordering": ["run", "series", "month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "series", "month"), name="forecast_point_uniq"
                    )
                ],
            },
        ),
    ]
