# Generated by Django 6.1 on 2026-10-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("service", "Сервис (наряды)"),
                            ("shop", "Реализация и розница"),
                            ("total", "Всего"),
                        ],
                        max_length=20,
                        verbose_name="Ряд",
                    ),
                ),
                ("month", models.DateField(verbose_name="Месяц")),
                ("share", models.FloatField(verbose_name="Доля группы в ряду")),
                ("revenue", models.FloatField(verbose_name="Прогноз выручки")),
                ("qty", models.FloatField(default=0, verbose_name="Прогноз, шт.")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.itemgroup",
                        verbose_name="Товарная группа",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="forecast.forecastrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз по группе",
                "verbose_name_plural": "Прогноз по группам",
                "ordering": ["run", "series", "month", "-revenue"],
                "indexes": [
                    models.Index(
                        fields=["run", "group"], name="forecast_fo_run_id_da3b81_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ForecastItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("service", "Сервис (наряды)"),
                            ("shop", "Реализация и розница"),
                            ("total", "Всего"),
                        ],
                        max_length=20,
                        verbose_name="Ряд",
                    ),
                ),
                ("month", models.DateField(verbose_name="Месяц")),
                ("qty", models.FloatField(verbose_name="Прогноз, шт.")),
                ("revenue", models.FloatField(verbose_name="Прогноз выручки")),
                ("price", models.FloatField(null=True, verbose_name="Цена")),
                (
                    "price_source",
                    models.CharField(
                        choices=[
                            ("6m", "медиана за 6 мес."),
                            ("12m", "медиана за 12 мес."),
                            ("last", "последняя продажа"),
                            ("group", "медиана группы"),
                            ("none", "нет цены"),
                        ],
                        max_length=10,
                        verbose_name="Откуда цена",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.itemgroup",
                        verbose_name="Товарная группа",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.item",
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="forecast.forecastrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз по артикулу",
                "verbose_name_plural": "Прогноз по артикулам",
                "ordering": ["run", "series", "month", "-qty"],
                "indexes": [
                    models.Index(
                        fields=["run", "item"], name="forecast_fo_run_id_83bac5_idx"
                    ),
                    models.Index(
                        fields=["run", "group"], name="forecast_fo_run_id_0a633f_idx"
                    ),
                ],
            },
        ),
    ]
