# Generated by Django 6.1 on 2026-10-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("forecast", "0002_forecastgroup_forecastitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemDemandStats",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        db_column="item_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="catalog.item",
                        verbose_name="Артикул",
                    ),
                ),
                ("qty12", models.FloatField(verbose_name="Продано за 12 мес., шт.")),
                (
                    "months12",
                    models.IntegerField(verbose_name="Месяцев с продажами из 12"),
                ),
                ("mean12", models.FloatField(verbose_name="Среднее в месяц")),
                ("std12", models.FloatField(verbose_name="Std в месяц")),
                ("cv12", models.FloatField(null=True, verbose_name="CV")),
                ("qty24", models.FloatField(verbose_name="Продано за 24 мес., шт.")),
                (
                    "months24",
                    models.IntegerField(verbose_name="Месяцев с продажами из 24"),
                ),
                (
                    "first_sale",
                    models.DateField(null=True, verbose_name="Первая продажа"),
                ),
                (
                    "last_sale",
                    models.DateField(null=True, verbose_name="Последняя продажа"),
                ),
                (
                    "last_cost",
                    models.FloatField(
                        null=True, verbose_name="Себестоимость последняя, ₽/шт."
                    ),
                ),
                (
                    "last_cost_date",
                    models.DateField(null=True, verbose_name="Дата себестоимости"),
                ),
            ],
            options={
                "verbose_name": "Статистика спроса",
                "verbose_name_plural": "Статистика спроса",
                "db_table": "mart_fc_item_stats",
                "managed": False,
            },
        ),
    ]
