# Generated by Django 6.1 on 2026-10-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0003_itemdemandstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="QtyCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                ("data_end", models.DateField(verbose_name="Факт по")),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="Месяцев вперёд"
                    ),
                ),
                (
                    "tune_runs",
                    models.JSONField(
                        default=dict, verbose_name="Подборы (прогноз выручки)"
                    ),
                ),
                ("seconds", models.FloatField(default=0, verbose_name="Время, c")),
            ],
            options={
                "verbose_name": "Проверка штук",
                "verbose_name_plural": "Проверки штук",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="forecastrun",
            name="families",
            field=models.BooleanField(
                default=False,
                help_text="Старые номера посчитаны вместе с актуальным (замены номеров)",
                verbose_name="Штуки по семействам номеров",
            ),
        ),
        migrations.CreateModel(
            name="QtyCheckPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cutoff", models.DateField(verbose_name="Отсечка")),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("items", "Как сейчас — каждый номер отдельно"),
                            ("families", "Со склейкой номеров"),
                        ],
                        max_length=10,
                        verbose_name="Вариант",
                    ),
                ),
                (
                    "items",
                    models.PositiveIntegerField(default=0, verbose_name="Артикулов"),
                ),
                ("actual", models.FloatField(verbose_name="Факт, шт.")),
                ("forecast", models.FloatField(verbose_name="Прогноз, шт.")),
                ("abs_err", models.FloatField(verbose_name="Σ |ошибка|, шт.")),
                (
                    "fam_actual",
                    models.FloatField(
                        default=0, verbose_name="Факт по семействам, шт."
                    ),
                ),
                (
                    "fam_forecast",
                    models.FloatField(
                        default=0, verbose_name="Прогноз по семействам, шт."
                    ),
                ),
                (
                    "fam_abs_err",
                    models.FloatField(
                        default=0, verbose_name="Σ |ошибка| по семействам, шт."
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="forecast.qtycheck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отсечка проверки штук",
                "verbose_name_plural": "Отсечки проверки штук",
                "ordering": ["run", "cutoff", "variant"],
            },
        ),
    ]
