# Generated by Django 6.1 on 2026-10-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Префикс"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="Салон"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=60, verbose_name="Город"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Работает"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
                "ordering": ["prefix"],
            },
        ),
        migrations.CreateModel(
            name="SalesDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Наряд (сервис)"),
                            ("sale", "Реализация"),
                            ("retail", "Розница"),
                            ("return", "Возврат"),
                            ("correction", "Корректировка"),
                            ("other", "Прочее"),
                        ],
                        db_index=True,
                        max_length=12,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(max_length=80, verbose_name="Вид документа 1С"),
                ),
                ("number", models.CharField(max_length=40, verbose_name="Номер")),
                ("dt", models.DateTimeField(verbose_name="Дата и время")),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docs",
                        to="sales.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ продажи",
                "verbose_name_plural": "Документы продаж",
                "ordering": ["-dt"],
            },
        ),
        migrations.CreateModel(
            name="SalesLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="Кол-во"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Пусто — строка без выручки (например, гарантийный наряд)",
                        max_digits=16,
                        null=True,
                        verbose_name="Выручка с НДС",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesdoc",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="catalog.item",
                        verbose_name="Артикул",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка продажи",
                "verbose_name_plural": "Строки продаж",
                "ordering": ["-doc__dt", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="salesdoc",
            constraint=models.UniqueConstraint(
                fields=("doc_type", "number", "dt"), name="sales_doc_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="salesline",
            index=models.Index(
                fields=["item", "doc"], name="sales_sales_item_id_23fa80_idx"
            ),
        ),
    ]
